name: workflow

on:
  pull_request:
    types:
      - opened
      - edited
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v4
        with: { go-version: '1.20' }

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with: { terraform_version: '1.9.0' }

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: '3.x'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: install terraform-docs
        uses: terraform-docs/gh-actions@v1.4.1
        with:
          working-dir: .
          git-push: "false"
          config-file: ./.terraform-docs.yml
      - name: Run tests
        run: |
          task test-terraform
      - name: Check git status
        run: |
          status=$(git status --porcelain)
          if [ -n "${status}" ]; then
            echo "Diff in generated files and/or formatting:"
            echo "${status}"
            exit 1
          fi
